import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"

function guard(session: unknown): session is { user: { id: string; role: string } } {
  return (
    typeof session === "object" &&
    session !== null &&
    "user" in session &&
    typeof (session as { user: unknown }).user === "object" &&
    (session as { user: { id: unknown; role: unknown } }).user !== null &&
    typeof (session as { user: { id: unknown } }).user.id === "string" &&
    typeof (session as { user: { role: unknown } }).user.role === "string"
  )
}

function requireRole(session: unknown, roles: string[]) {
  if (!guard(session)) return false
  return roles.includes(session.user.role)
}

export async function DELETE(req: Request, { params }: { params: { id: string } }) {
  try {
    const session = await getServerSession(authOptions)
    if (!requireRole(session, ["warehouse", "owner", "procurement"])) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 })
    }
    
    const gr = await prisma.goodsReceipt.findUnique({
      where: { id: params.id },
      include: { po: true }
    })

    if (!gr) return NextResponse.json({ error: "Goods Receipt not found" }, { status: 404 })

    await prisma.$transaction(async (tx) => {
      await tx.goodsReceipt.delete({ where: { id: params.id } })
      
      const remainingGRs = await tx.goodsReceipt.count({ where: { poId: gr.poId } })
      
      if (remainingGRs === 0) {
        // Reset PO to SENT
        await tx.purchaseOrder.update({
          where: { id: gr.poId },
          data: { status: "SENT", dateReceived: null }
        })
        
        // Reset qtyReceived on all line items
        await tx.pOLineItem.updateMany({
          where: { poId: gr.poId },
          data: { qtyReceived: 0, condition: null }
        })
        
        // Clear alerts generated by the receipt
        await tx.alert.deleteMany({
          where: { poId: gr.poId }
        })
      } else {
        // Fallback: set to PARTIAL, because we can't reliably subtract the exact quantities 
        // without a GoodsReceiptItem table
        await tx.purchaseOrder.update({
          where: { id: gr.poId },
          data: { status: "PARTIAL" }
        })
      }
    })

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error(error)
    return NextResponse.json({ error: "Failed to delete goods receipt" }, { status: 500 })
  }
}
